// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentRestApi.Model;

#nullable disable

namespace StudentRestApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241018091914_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentRestApi.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Department = 0,
                            Email = "Adam@test.com",
                            FirstName = "Adam",
                            Gender = 0,
                            LastName = "Adam",
                            PhotoPath = "Images/Adam.png"
                        },
                        new
                        {
                            StudentId = 2,
                            Department = 0,
                            Email = "Anna@test.com",
                            FirstName = "Anna",
                            Gender = 1,
                            LastName = "Anna",
                            PhotoPath = "Images/Anna.png"
                        },
                        new
                        {
                            StudentId = 3,
                            Department = 0,
                            Email = "Kris@test.com",
                            FirstName = "Kris",
                            Gender = 0,
                            LastName = "Kris",
                            PhotoPath = "Images/Kris.png"
                        },
                        new
                        {
                            StudentId = 4,
                            Department = 0,
                            Email = "Filip@test.com",
                            FirstName = "Filip",
                            Gender = 0,
                            LastName = "Filip",
                            PhotoPath = "Images/Filip.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
